### ISSUE TITLE
preprocess

### ISSUE THREAD

**Issue by qiupinghust** [BGIResearch/stereopy#4]
- filter

- [x] filter bins by  total_count, n_genes_by_count, mt_gene_pt and bins_list.
- [x] filter genes by gene count and genes_list.
- [x] filter bins by position.

- normalize
- [x] total normalize
- [x] quantile normalize
- [x] z-score normalize
- [x] sc_transform
- [ ] recipes seruat

- qc
- [x] total count
- [x] n_gene_by_count
- [x] mt_gene_pt

**Comment by wanruiwen-genomics-cn** [comment]
Dear @qiupinghust,

Thank you for tracking the preprocessing feature development!

**Short answer:** This issue is a development checklist for preprocessing capabilities, and most items have been successfully implemented. The remaining item is the Seurat recipes normalization.

---

## Assessment
- **Type:** feature request (development tracking)
- **Severity:** low
- **Affected module:** `stereo/tools/`, `stereo/core/st_pipeline.py`

## What Is Happening
This issue serves as a progress tracker for Stereopy's preprocessing pipeline. The checklist covers three main areas:

1. **Filtering** — bin filtering by total_count, n_genes_by_count, mt_gene_pt, and bins_list; gene filtering by gene count and genes_list; and spatial position-based filtering. All items are marked complete.
2. **Normalization** — total normalize, quantile normalize, z-score normalize, and sc_transform are complete. The Seurat recipes normalization (`recipes_seurat`) remains unimplemented.
3. **QC** — total count, n_gene_by_count, and mt_gene_pt are all complete.

## Current Status
Nearly all preprocessing features in this checklist have been implemented. The only outstanding item is **recipes Seurat** normalization, which would replicate the `Seurat::NormalizeData` + `FindVariableFeatures` + `ScaleData` workflow.

## Notes
- This issue is a development progress tracker rather than a bug report.
- The remaining `recipes_seurat` item could be addressed in a dedicated feature PR if there is continued interest.
- The existing `sctransform` implementation (in `stereo/algorithm/sctransform/`) already covers a significant portion of the Seurat normalization workflow.

Please let us know if you have further questions or if the Seurat recipes feature is still a priority!

Best regards,
Stereopy Maintainer
