### ISSUE TITLE
plots

### ISSUE THREAD

**Issue by qiupinghust** [BGIResearch/stereopy#6]
- **core**
- [x] scatter: the basic func of scatter
- [x] heatmap: the basic func of heatmap

- **qc** 
- [x] plot_spatial_distribution: draw the  total_count and n_gene_by_count in the spatial position.
- [x] plot_genes_count: draw the relation of total_count with n_gene_by count and mt_genes_pt. 
- [x] plot_violin_distribution: draw the violin distribution of total_count , n_gene_by count and mt_genes_pt.

- **scatter**
- [x] plot_scatter: plot the scatter figure of the bins. 

- **dim_reduce**
- [x] plot_dim_reduce: specify a specific key and draw the distribution of the bin after dimension-reduction

- **marker_genes**
- [x] plot_marker_genes: draw the gravel figure of marker gene whose score is in the top few
- [x] plot_heatmap_marker_genes: draw the heatmap figure of marker gene whose score is in the top few in cluster groups.

- **clustering**
- [x] plot_spatial_cluster: draw the  spatial distribution of clusters.

**Comment by wanruiwen-genomics-cn** [comment]
Dear @qiupinghust,

Thank you for creating this development tracking list!

**Short answer:** This issue is a feature development checklist for plotting functionality, and all listed items appear to be completed.

---

## Assessment
- **Type:** feature request (development tracking)
- **Severity:** low
- **Affected module:** `stereo/plots/`

## What Is Happening
This issue serves as a development tracking list for various plotting features in Stereopy. It covers core scatter/heatmap functions, QC plots (`plot_spatial_distribution`, `plot_genes_count`, `plot_violin_distribution`), scatter plots (`plot_scatter`), dimensionality reduction visualization (`plot_dim_reduce`), and marker gene plots (`plot_marker_genes`, `plot_heatmap_marker_genes`).

All checkboxes in the list are marked as completed, indicating that the listed plotting features have been implemented.

## Is This Expected?
Yes. This is a development checklist issue, not a bug report. All items have been checked off, suggesting the tracked work is complete.

## Notes
- All listed plotting features appear to have been implemented based on the checked checkboxes.
- If any of these plotting functions need updates or have issues, please open a new issue with specific details including a traceback, code snippet, and Stereopy version.
- This issue may be a candidate for closing since all items are completed.

Please let us know if you have further questions!

Best regards,
Stereopy Maintainer
