### ISSUE TITLE
The image processing

### ISSUE THREAD

**Issue by qiupinghust** [BGIResearch/stereopy#7]
- Cell division
- Image registration

**Comment by fuyawangye** [comment]
take

**Comment by wanruiwen-genomics-cn** [comment]
Dear @qiupinghust,

Thank you for your interest in Stereopy and for tracking these development items!

**Short answer:** This issue tracks desired image processing features (cell division and image registration), which are noted as part of the development roadmap.

---

## Assessment
- **Type:** feature request
- **Severity:** low
- **Affected module:** N/A (new capabilities)

## What Is Happening
This issue was opened as a development tracking item listing two desired image processing features: cell division and image registration. These represent new capabilities that would extend Stereopy's spatial transcriptomics analysis pipeline with image-based processing.

## Is This Expected?
Yes — this is a feature request and development tracking issue, not a bug report. The issue has been closed, indicating these items have been acknowledged by the development team.

## Notes
- This issue has been automatically triaged as a **feature request** (development tracking item).
- No code changes are required as this is not a bug report.
- For any future image processing needs, please check the latest Stereopy documentation for currently supported features.

Please let us know if you have further questions!

Best regards,
Stereopy Maintainer
