### ISSUE TITLE
开发文档说明

### ISSUE THREAD

**Issue by qiupinghust** [BGIResearch/stereopy#9]
### 设计思路

- IO：文件数据读写，生成数据类，目前使用AnnData
- 预处理：对数据类进行质控、过滤、标准化
- 分析：输入数据类以及相应参数设置，运行分析，将分析结果写回数据类
- 可视化：对分析结果进行可视化

  框架流程图

    ![image](./source/schema.png)

### 设计原则

**1.模块化**

考虑到框架的可拓展性，主要设计了三种基类，分别为数据类、分析类、结果类。整体实现流程是将数据类传入分析类，进行分析，
得到结果类，将结果写回数据类，或者输出文件，并可视化结果。

**2.基类说明**

- **数据基类（StereoData）**

  _下一版增加，目前暂时使用AnnData_
```text
Class StereoData:
    pass
```

- **分析基类（ToolBase）**
```text
Class ToolBase(data, method, name=None):
   参数：
     data：分析数据，AnnData（下一版调为StereoData）
     method: 分析方法，str
     name：分析名字，str，作为结果存取的key
   属性：
     self.data
     self.method
     self.name
     self.exp_matrix
   方法  
     check_param(): 检查参数
     sparse2array(): 将self.exp_matrix稀疏矩阵转换成np.array
     get_params(var_info): 获取参数变量名以及相应的值
     add_result(): 保存分析结果
```

- **结果基类（StereoResult）**
```text
Class StereoResult(name='stereo', param=None):
  参数：
    name： 名称， str
    param：参数信息，dict
  属性：
    self.name
    self.param
  方法：
    update_params(v): 更新参数
    __str__(): 返回类的参数信息及结果信息
    __repr__()：打印类的参数信息及结果信息
```

### 开发说明

1 **tool分析模块开发**
  tool分析模块主要包含两个内容的开发，分别为分析类以及结果类的开发。

1.1 **分析子类编写**
    
1.1.1 子类需继承基类，以及主要重写和实现相关的方法
- 获取参数
- 继承父类构造方法，必须要有的参数：data、method、name
- 重写参数检查方法: self.check_param()
- 实现分析运行方法: self.fit()
        
1.1.2 可自定义分析需要的参数跟方法

**编写示例：**
        
```python
from ..core.tool_base import ToolBase
from ..log_manager import logger


class DimReduce(ToolBase):
    def __init__(self, data: AnnData, method='pca', n_pcs=2, min_variance=0.01, n_iter=250,
                 n_neighbors=5, min_dist=0.3, inplace=False, name='dim_reduce'):
        # 获取参数
        self.params = self.get_params(locals())
        # 继承父类构造方法
        super(DimReduce, self).__init__(data=data, method=method, name=name)
        # 参数检查
        self.check_param()
        # 自定义分析所需属性，结合分析需要
        self.n_pcs = n_pcs
        self.min_variance = min_variance
        self.n_iter = n_iter
        self.n_neighbors = n_neighbors
        self.min_dist = min_dist
        self.result = DimReduceResult(name=name, param=self.params)
     
    def check_param(self): #  重写参数检查方法，根据分析所传参数以及其值范围进行检查约束
        """
        Check whether the parameters meet the requirements.
        :return:
        """
        super(DimReduce, self).check_param()
        if self.method.lower() not in ['pca', 'tsen', 'umap', 'factor_analysis', 'low_variance']:
            logger.error(f'{self.method} is out of range, please check.')
            raise ValueError(f'{self.method} is out of range, please check.')
    
    def fit(self, exp_matrix=None):
        # 自定义分析方法实现逻辑
        exp_matrix = exp_matrix if exp_matrix is not None else self.exp_matrix
        if self.method == 'low_variance':
            self.result.x_reduce = low_variance(exp_matrix, self.min_variance)
        elif self.method == 'umap':
            self.result.x_reduce = u_map(exp_matrix, self.n_pcs, self.n_neighbors, self.min_dist)
        else:
            pca_res = pca(exp_matrix, self.n_pcs)
            self.result.x_reduce = pca_res['x_pca']
            self.result.variance_ratio = pca_res['variance_ratio']
            self.result.variance_pca = pca_res['variance']
            self.result.pcs = pca_res['pcs']
         # 通过self.add_result()添加结果回数据类
        self.add_result(result=self.result, key_added=self.name)
``` 
     
1.2 **结果子类编写**
    
- 子类需继承结果基类

- 根据分析结果，自定义该结果类存放的内容以及实现的方法

**编写示例：**
        
```python
class FindMarkerResult(StereoResult):
    def __init__(self, name: str = 'find_marker', param: Optional[dict] = None,
                 degs_data: Optional[pd.DataFrame] = None):
        super(FindMarkerResult, self).__init__(name, param)
        self.degs_data = degs_data

    def __str__(self):
        info = super(FindMarkerResult, self).__str__()
        if self.degs_data is not None:
            info += f'    result: a DataFrame which has `genes`,`pvalues`,`pvalues_adj`, `log2fc`, `score` columns.\n'
            info += f'    the shape is: {self.degs_data.shape}'
        return info

    def top_k_marker(self, top_k_genes=10, sort_key='pvalues', ascend=False):
        """
        obtain the first k significantly different genes
        :param top_k_genes:  the number of top k
        :param sort_key: sort by the column
        :param ascend: the ascend order of sorting.
        :return:
        """
        if self.degs_data is not None:
            top_k_data = self.degs_data.sort_values(by=sort_key, ascending=ascend).head(top_k_genes)
            return top_k_data
        else:
            logger.warning('the result of degs is None, return None.')
            return None
```

2 **可视化模块** 

- 绘图基础单元目前包含热图以及散点图
- 每个可视化功能，主要基于分析需展示的结果来决定
- 目前传入数据类主要是anndata，但在获取绘图数据时，应尽可能与anndata抽离，可针对结果类进行数据获取的函数
- 目前采用的面向过程编程，后续看下是否需要改成面向对象

3 **书写规范**
  1. 编码要求符合pep8编写规范
  2. 文件命名统一采用小写、下划线；类的命名采用驼峰命名法。
       > eg：文件名：dim_reduce.py   类名：DimReduce
  3. 变量命名采用小写，应该尽可能有意义，避免采用无意的命名，如：a=1， b=2等等
  4. 注释信息要完善，每个函数应该编写其注释信息
  5. 建议使用pycharm进行编辑，编辑器可自动检查编写的代码是否符合规范，且有相关提示。其他编辑器也可以借助安装相关插件来检查。
       ![image](https://raw.githubusercontent.com/BGIResearch/stereopy/dev/docs/source/code_format.png)

**Comment by qiupinghust** [comment]
**框架概述**

**编码要求**
1. 编码要求符合pep8编写规范
2. 文件命名统一采用小写、下划线；类的命名采用驼峰命名法。
    > eg：文件名：dim_reduce.py   类名：DimReduce
3. 变量命名采用小写，应该尽可能有意义，避免采用无意的命名，如：a=1， b=2等等
4. 注释信息要完善，每个函数应该编写其注释信息
5. 建议使用pycharm进行编辑，编辑器可自动检查编写的代码是否符合规范，且有相关提示。其他编辑器也可以借助安装相关插件来检查。
![image](https://raw.githubusercontent.com/BGIResearch/stereopy/dev/docs/source/code_format.png)

**Comment by wanruiwen-genomics-cn** [comment]
Dear @qiupinghust,

Thank you for providing this comprehensive development documentation!

**Short answer:** This is a well-structured internal development guide describing Stereopy's modular architecture and contribution patterns. No code fix is required.

---

## Assessment
- **Type:** documentation / feature request
- **Severity:** low
- **Affected module:** project-wide (framework design document)

## What Is Happening
This issue serves as an internal development reference describing:
1. The framework's modular design with three base classes (`StereoData`, `ToolBase`, `StereoResult`)
2. The analysis pipeline flow: IO → preprocessing → analysis → visualization
3. Guidelines for implementing new tool analysis modules and result classes
4. Coding standards (PEP8, naming conventions, documentation requirements)

## Is This Expected?
Yes — this is an informational documentation issue, not a bug report. The design patterns described here are consistent with the current Stereopy architecture (though the codebase has evolved significantly since this was written, e.g., `StereoExpData` now uses its own data model rather than relying directly on AnnData as the primary interface).

## Notes
- The current codebase has evolved from this original design: `StereoExpData` is now the primary data container with AnnData as the underlying storage backend
- Tool registration now uses the `StPipeline` class with the `@logit` decorator pattern
- Results are managed through the `Result` class with categorized key routing
- This documentation may benefit from updates to reflect the current architecture

Please let us know if you have further questions!

Best regards,
Stereopy Maintainer
